title: Elmar Jansen
email: elmar@elmarjansen.nl
description: >- # this means to ignore newlines until "baseurl:"
  Homepage Elmar Jansen, GroenLinks duo-lid Stadsdeelcommissie Amsterdam Centrum, 
  docent Universiteit van Amsterdam (Politicoloog), datanerd, open-source programmeur 
  en (amateur) muzikant.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://elmarjansen.nl" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: elmarj
github_username:  elmarj
remote_theme: b2a3e8/jekyll-theme-console

# jekyll-theme-console settings:
header_pages:
  - index.md
style: dark # dark (default), light or hacker
listen_for_clients_preferred_style: true # false (default) or true
footer: '<a href="https://twitter.com/elmarj" rel="me">twitter</a> | <a href="https://www.goodreads.com/user/show/11607541-elmar-jansen" rel="me">goodreads</a> | <a href="https://github.com/elmarj" rel="me">github</a> | <a href="https://facebook.com/elmarj" rel="me">facebook</a> | <a href="https://www.linkedin.com/in/elmarjansen/" rel="me">linkedin</a><br>e-mail: <a href="mailto:elmar@elmarjansen.nl" rel="me">elmar@elmarjansen.nl</a>'
