title: Elmar Jansen
email: elmar@elmarjansen.nl
description: >- # this means to ignore newlines until "baseurl:"
  Homepage Elmar Jansen, GroenLinks duo-lid Stadsdeelcommissie Amsterdam Centrum, 
  docent Universiteit van Amsterdam (Politicoloog), datanerd, open-source programmeur 
  en (amateur) muzikant.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://elmarjansen.nl" # the base hostname & protocol for your site, e.g. http://example.com
name: Elmar Jansen
picture: /elmar.jpg
twitter_username: elmarj
github_username:  elmarj
linkedin_username: elmarjansen
facebook_username: elmarjansen
remote_theme: ElmarJ/jekyll-theme-console

# jekyll-theme-console settings:
header_pages:
  - index.md
style: dark # dark (default), light or hacker
listen_for_clients_preferred_style: true # false (default) or true
footer: ''
